# default config: https://github.com/troessner/reek/blob/master/docs/defaults.reek.yml
# detectors' docs: https://github.com/troessner/reek/tree/master/docs
---
exclude_paths:
  - 'bin/'
  - 'spec/'

detectors:
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 4 # +1 to default value
    overrides:
      initialize:
        max_params: 6 # +1 to default value
  ModuleInitialize:
    enabled: false
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 5 # +1 to default value
  DataClump:
    exclude:
      - Flows::Result::Helpers
      - Flows::SharedContextPipeline::DSL::Tracks
  IrresponsibleModule:
    exclude:
      - Flows::SharedContextPipeline
  FeatureEnvy:
    exclude:
      - Flows::SharedContextPipeline#call
      - Flows::Contract # too many false positives here
  TooManyStatements:
    exclude:
      - Flows::SharedContextPipeline#call
      - initialize
  DuplicateMethodCall:
    exclude:
      - Flows::SharedContextPipeline#call
      - 'length'
  MissingSafeMethod:
    exclude:
      - Flows::Contract
