inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/WhileUntilModifier:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - '**/*.md'
    - 'spec/**/*'

Style/MixinUsage:
  Exclude:
    - '**/*.md'

Lint/UnusedMethodArgument:
  Exclude:
    - '**/*.md'

Lint/UnusedBlockArgument:
  Exclude:
    - '**/*.md'

Style/CaseEquality:
  Exclude:
    - 'lib/flows/contract/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Style/Documentation:
  Exclude:
    - 'lib/flows/shared_context_pipeline/step.rb' # false positive here

Style/SlicingWithRange:
  Enabled: false # to support Ruby 2.5
